/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package entornografico.empleados;

import entornografico.lectores.*;
import entornografico.libros.*;
import entornografico.prestamos.*;
import javax.swing.JOptionPane;

/**
 *
 * @author 54349
 */
public class GestionOpciones extends javax.swing.JFrame {

    /**
     * Creates new form GestionOpciones
     */
    public GestionOpciones() {
        initComponents();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoBtnLectores = new javax.swing.ButtonGroup();
        grupoBtnLibros = new javax.swing.ButtonGroup();
        grupoBtnPrestamos = new javax.swing.ButtonGroup();
        grupoBtnEmpleados = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnAceptarLec = new javax.swing.JButton();
        rbAgregarLector = new javax.swing.JRadioButton();
        rbMostrarLectores = new javax.swing.JRadioButton();
        rbMostrarLibrosPrestadosLector = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnAceptarLib = new javax.swing.JButton();
        rbAgregarLibro = new javax.swing.JRadioButton();
        rbBorrarLibro = new javax.swing.JRadioButton();
        rbMostrarLibros = new javax.swing.JRadioButton();
        rbBuscarLibro = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnAceptarP = new javax.swing.JButton();
        rbAgregarPrestamo = new javax.swing.JRadioButton();
        rbDevolucion = new javax.swing.JRadioButton();
        rbPrestamosNoDevueltos = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        rbAgregarEmpleado = new javax.swing.JRadioButton();
        rbBorrarEmpleado = new javax.swing.JRadioButton();
        btnAceptarEmp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Maiandra GD", 0, 36)); // NOI18N
        jLabel1.setText("¡Bienvenido/a!");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\54349\\OneDrive\\Documentos\\ImagenLibros.jpg")); // NOI18N
        jLabel5.setText("Salir");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, 0, 510, 310));

        jTabbedPane1.addTab("Inicio", jPanel1);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Seleccione la Operación que desea realizar");

        btnAceptarLec.setText("Aceptar");
        btnAceptarLec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarLecActionPerformed(evt);
            }
        });

        grupoBtnLectores.add(rbAgregarLector);
        rbAgregarLector.setText("Agregar Lector");

        grupoBtnLectores.add(rbMostrarLectores);
        rbMostrarLectores.setText("Mostrar lista de Lectores");

        grupoBtnLectores.add(rbMostrarLibrosPrestadosLector);
        rbMostrarLibrosPrestadosLector.setText("Mostrar Libros prestados a un Lector");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbMostrarLibrosPrestadosLector)
                    .addComponent(rbMostrarLectores)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(rbAgregarLector)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAceptarLec))
                        .addComponent(jLabel2)))
                .addGap(87, 87, 87))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(rbAgregarLector)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbMostrarLectores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbMostrarLibrosPrestadosLector)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(btnAceptarLec)
                .addGap(110, 110, 110))
        );

        jTabbedPane1.addTab("Lectores", jPanel2);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Seleccione la Operación que desea realizar");

        btnAceptarLib.setText("Aceptar");
        btnAceptarLib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarLibActionPerformed(evt);
            }
        });

        grupoBtnLibros.add(rbAgregarLibro);
        rbAgregarLibro.setText("Agregar Libro");

        grupoBtnLibros.add(rbBorrarLibro);
        rbBorrarLibro.setText("Borrar Libro");

        grupoBtnLibros.add(rbMostrarLibros);
        rbMostrarLibros.setText("Mostrar Libros disponibles");

        grupoBtnLibros.add(rbBuscarLibro);
        rbBuscarLibro.setText("Buscar cantidad disponible de un Libro");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbBuscarLibro)
                    .addComponent(rbMostrarLibros)
                    .addComponent(rbBorrarLibro)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(rbAgregarLibro)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAceptarLib))
                        .addComponent(jLabel3)))
                .addGap(87, 87, 87))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(rbAgregarLibro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbBorrarLibro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbMostrarLibros)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbBuscarLibro)
                .addGap(2, 2, 2)
                .addComponent(btnAceptarLib)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Libros", jPanel3);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Seleccione la Operación que desea realizar");

        btnAceptarP.setText("Aceptar");
        btnAceptarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarPActionPerformed(evt);
            }
        });

        grupoBtnPrestamos.add(rbAgregarPrestamo);
        rbAgregarPrestamo.setText("Agregar Préstamo");

        grupoBtnPrestamos.add(rbDevolucion);
        rbDevolucion.setText("Registrar Devolución");

        grupoBtnPrestamos.add(rbPrestamosNoDevueltos);
        rbPrestamosNoDevueltos.setText("Mostrar Préstamos de Libros aún no devueltos");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbPrestamosNoDevueltos)
                    .addComponent(rbAgregarPrestamo)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnAceptarP)
                        .addComponent(jLabel4))
                    .addComponent(rbDevolucion))
                .addGap(87, 87, 87))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(rbAgregarPrestamo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbDevolucion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbPrestamosNoDevueltos)
                .addGap(14, 14, 14)
                .addComponent(btnAceptarP)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Préstamos", jPanel4);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Seleccione la Operación que desea realizar");

        grupoBtnEmpleados.add(rbAgregarEmpleado);
        rbAgregarEmpleado.setText("Agregar Nuevo Empleado");

        grupoBtnEmpleados.add(rbBorrarEmpleado);
        rbBorrarEmpleado.setText("Borrar Empleado");

        btnAceptarEmp.setText("Aceptar");
        btnAceptarEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarEmpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAceptarEmp)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(rbBorrarEmpleado)
                        .addComponent(rbAgregarEmpleado)
                        .addComponent(jLabel6)))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(rbAgregarEmpleado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbBorrarEmpleado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAceptarEmp)
                .addContainerGap(145, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Empleados", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarLecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarLecActionPerformed
        if (rbAgregarLector.isSelected()) {
            AgregarLector agregarLector = new AgregarLector();
            agregarLector.setVisible(true);
            agregarLector.setLocationRelativeTo(null);
            this.dispose();
        } else if (rbMostrarLectores.isSelected()) {
            MostrarLectores mostrarLectores = new MostrarLectores();
            mostrarLectores.setVisible(true);
            mostrarLectores.setLocationRelativeTo(null);
            this.dispose();
        } else if (rbMostrarLibrosPrestadosLector.isSelected()) {
            LibrosPrestadosALector librosPrestadosALector = new LibrosPrestadosALector();
            librosPrestadosALector.setVisible(true);
            librosPrestadosALector.setLocationRelativeTo(null);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, selecciona una opción.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAceptarLecActionPerformed

    private void btnAceptarLibActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarLibActionPerformed
        if (rbAgregarLibro.isSelected()) {
            AgregarLibro agregarLibro = new AgregarLibro();
            agregarLibro.setVisible(true);
            agregarLibro.setLocationRelativeTo(null);
            this.dispose();
        } else if (rbBorrarLibro.isSelected()) {
            BorrarLibro borrarLibro = new BorrarLibro();
            borrarLibro.setVisible(true);
            borrarLibro.setLocationRelativeTo(null);
            this.dispose();
        } else if (rbMostrarLibros.isSelected()) {
            LibrosDisponibles librosDisponibles = new LibrosDisponibles();
            librosDisponibles.setVisible(true);
            librosDisponibles.setLocationRelativeTo(null);
            this.dispose();
        } else if (rbBuscarLibro.isSelected()) {
            CantidadLibro cantidadLibro = new CantidadLibro();
            cantidadLibro.setVisible(true);
            cantidadLibro.setLocationRelativeTo(null);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, selecciona una opción.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAceptarLibActionPerformed

    private void btnAceptarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarPActionPerformed
        if (rbAgregarPrestamo.isSelected()) {
            AgregarPrestamo agregarPrestamo = new AgregarPrestamo();
            agregarPrestamo.setVisible(true);
            agregarPrestamo.setLocationRelativeTo(null);
            this.dispose();
        } else if (rbDevolucion.isSelected()) {
            RegistrarDevolucion registrarDevolucion = new RegistrarDevolucion();
            registrarDevolucion.setVisible(true);
            registrarDevolucion.setLocationRelativeTo(null);
            this.dispose();
        } else if (rbPrestamosNoDevueltos.isSelected()) {
            PrestamosNoDevueltos prestamosNoDevueltos = new PrestamosNoDevueltos();
            prestamosNoDevueltos.setVisible(true);
            prestamosNoDevueltos.setLocationRelativeTo(null);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, selecciona una opción.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAceptarPActionPerformed

    private void btnAceptarEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarEmpActionPerformed
        if (rbAgregarEmpleado.isSelected()) {
            CrearUsuario crearUsuario = new CrearUsuario();
            crearUsuario.setVisible(true);
            crearUsuario.setLocationRelativeTo(null);
            this.dispose();
        } else if (rbBorrarEmpleado.isSelected()) {
            BorrarEmpleado borrarEmpleado = new BorrarEmpleado();
            borrarEmpleado.setVisible(true);
            borrarEmpleado.setLocationRelativeTo(null);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, selecciona una opción.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAceptarEmpActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptarEmp;
    private javax.swing.JButton btnAceptarLec;
    private javax.swing.JButton btnAceptarLib;
    private javax.swing.JButton btnAceptarP;
    private javax.swing.JButton btnSalir;
    private javax.swing.ButtonGroup grupoBtnEmpleados;
    private javax.swing.ButtonGroup grupoBtnLectores;
    private javax.swing.ButtonGroup grupoBtnLibros;
    private javax.swing.ButtonGroup grupoBtnPrestamos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JRadioButton rbAgregarEmpleado;
    private javax.swing.JRadioButton rbAgregarLector;
    private javax.swing.JRadioButton rbAgregarLibro;
    private javax.swing.JRadioButton rbAgregarPrestamo;
    private javax.swing.JRadioButton rbBorrarEmpleado;
    private javax.swing.JRadioButton rbBorrarLibro;
    private javax.swing.JRadioButton rbBuscarLibro;
    private javax.swing.JRadioButton rbDevolucion;
    private javax.swing.JRadioButton rbMostrarLectores;
    private javax.swing.JRadioButton rbMostrarLibros;
    private javax.swing.JRadioButton rbMostrarLibrosPrestadosLector;
    private javax.swing.JRadioButton rbPrestamosNoDevueltos;
    // End of variables declaration//GEN-END:variables
}
